name: Strategic Edge
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25145
title: Strategic Edge International
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f403b'
    - '#6e6b64'
    - '#a89c90'
    - '#030303'
    - '#ba393b'
  brandStrength: 0.12993249855935574
  lightness: 0.6371091906912625
  saturation: 0.9526977729983628
  rhythmicContrast: 0.3157743534538895
purpose: []
